### ISSUE TITLE
Add project authorization checks

### ISSUE THREAD

**Issue by larsduelfer** [NovatecConsulting/event-sourcing-with-axon#35]
Projects can be created by users that are project managers in a company. They automatically become a participant of the project.
Projects (and nested objects like tasks and participants) can be accessed and edited by users that are participants of the project.

---
Use Access Control List 

- generic layout (idea: colums aggregate type, identifier, permission, user identifier)
- event handler are filling this table based on the events.
- checks are done either in interceptor or in query direct

**Comment by dakr0013** [comment]
Implemented in #50
