### ISSUE TITLE
How will project and task rescheduled events influence each other's aggregate?

### ISSUE THREAD

**Issue by larsduelfer** [NovatecConsulting/event-sourcing-with-axon#4]
Display a project status (PLANNED, ONTIME, DELAYED, COMPLETED) based on project and tasks events
- Is this status just an attribute of a projection and derived from anyway existing data in the project and task events?
- Is this status a field of the aggregate and influenced by other events? 
- What is the benefit when just being an attribute of a projection and what if being a property of the aggregate?

**Comment by dakr0013** [comment]
implement other variant
